version: '3'
services:
  web:
    image: nginx:latest
    volumes:
      - ./:/site
      - ./docker-config/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8050:80"
    environment:
     - NGINX_PORT=80