export const cities = [
    'Akron',
    'Alliance',
    'Amherst',
    'Ashland',
    'Ashtabula',
    'Athens',
    'Aurora',
    'Avon',
    'Avon Lake',
    'Barberton',
    'Bay Village',
    'Beachwood',
    'Beavercreek',
    'Bedford',
    'Bedford Heights',
    'Bellbrook',
    'Bellefontaine',
    'Bellevue',
    'Belpre',
    'Berea',
    'Bexley',
    'Blue Ash',
    'Bowling Green',
    'Brecksville',
    'Broadview Heights',
    'Brook Park',
    'Brooklyn',
    'Brookville',
    'Brunswick',
    'Bryan',
    'Bucyrus',
    'Cambridge',
    'Campbell',
    'Canal Fulton',
    'Canal Winchester',
    'Canfield',
    'Canton',
    'Celina',
    'Centerville',
    'Chardon',
    'Cheviot',
    'Chillicothe',
    'Cincinnati',
    'Circleville',
    'Clayton',
    'Cleveland',
    'Cleveland Heights',
    'Clyde',
    'Columbiana',
    'Columbus',
    'Conneaut',
    'Cortland',
    'Coshocton',
    'Cuyahoga Falls',
    'Dayton',
    'Deer Park',
    'Defiance',
    'Delaware',
    'Delphos',
    'Dover',
    'Dublin',
    'East Cleveland',
    'East Liverpool',
    'Eastlake',
    'Eaton',
    'Elyria',
    'Englewood',
    'Euclid',
    'Fairborn',
    'Fairfield',
    'Fairlawn',
    'Fairview Park',
    'Findlay',
    'Forest Park',
    'Fostoria',
    'Franklin',
    'Fremont',
    'Gahanna',
    'Galion',
    'Garfield Heights',
    'Geneva',
    'Germantown',
    'Girard',
    'Grandview Heights',
    'Green',
    'Greenville',
    'Grove City',
    'Groveport',
    'Hamilton',
    'Harrison',
    'Heath',
    'Highland Heights',
    'Hilliard',
    'Hillsboro',
    'Hubbard',
    'Huber Heights',
    'Hudson',
    'Huron',
    'Independence',
    'Indian Hill',
    'Ironton',
    'Jackson',
    'Kent',
    'Kenton',
    'Kettering',
    'Kirtland',
    'Lakewood',
    'Lancaster',
    'Lebanon',
    'Lima',
    'Logan',
    'London',
    'Lorain',
    'Louisville',
    'Loveland',
    'Lyndhurst',
    'Macedonia',
    'Madeira',
    'Mansfield',
    'Maple Heights',
    'Marietta',
    'Marion',
    'Martins Ferry',
    'Marysville',
    'Mason',
    'Massillon',
    'Maumee',
    'Mayfield Heights',
    'Medina',
    'Mentor',
    'Mentor-on-the-Lake',
    'Miamisburg',
    'Middleburg Heights',
    'Middletown',
    'Milford',
    'Monroe',
    'Montgomery',
    'Moraine',
    'Mount Healthy',
    'Mount Vernon',
    'Munroe Falls',
    'Napoleon',
    'Nelsonville',
    'New Albany',
    'New Carlisle',
    'New Franklin',
    'New Philadelphia',
    'Newark',
    'Niles',
    'North Canton',
    'North College Hill',
    'North Olmsted',
    'North Ridgeville',
    'North Royalton',
    'Northwood',
    'Norton',
    'Norwalk',
    'Norwood',
    'Oakwood',
    'Oberlin',
    'Olmsted Falls',
    'Ontario',
    'Oregon',
    'Orrville',
    'Oxford',
    'Painesville',
    'Parma',
    'Parma Heights',
    'Pataskala',
    'Pepper Pike',
    'Perrysburg',
    'Pickerington',
    'Piqua',
    'Port Clinton',
    'Portsmouth',
    'Powell',
    'Ravenna',
    'Reading',
    'Reynoldsburg',
    'Richmond Heights',
    'Rittman',
    'Riverside',
    'Rocky River',
    'Rossford',
    'Salem',
    'Sandusky',
    'Seven Hills',
    'Shaker Heights',
    'Sharonville',
    'Sheffield Lake',
    'Shelby',
    'Sidney',
    'Solon',
    'South Euclid',
    'Springboro',
    'Springdale',
    'Springfield',
    'St. Clairsville',
    'St. Marys',
    'Steubenville',
    'Stow',
    'Streetsboro',
    'Strongsville',
    'Struthers',
    'Sylvania',
    'Tallmadge',
    'Tiffin',
    'Tipp City',
    'Toledo',
    'Toronto',
    'Trenton',
    'Trotwood',
    'Troy',
    'Twinsburg',
    'Uhrichsville',
    'Union',
    'University Heights',
    'Upper Arlington',
    'Upper Sandusky',
    'Urbana',
    'Van Wert',
    'Vandalia',
    'Vermilion',
    'Wadsworth',
    'Wapakoneta',
    'Warren',
    'Warrensville Heights',
    'Washington Court House',
    'Waterville',
    'Wauseon',
    'Wellston',
    'West Carrollton',
    'Westerville',
    'Westlake',
    'Whitehallv',
    'Wickliffe',
    'Willard',
    'Willoughby',
    'Willoughby Hills',
    'Willowick',
    'Wilmington',
    'Wooster',
    'Worthington',
    'Wyoming',
    'Xenia',
    'Youngstown',
    'Zanesville'
];